---
# tasks file for oh-my-zsh

  - package: name={{ item }} state=latest
    with_items:
      - zsh
      - git
    notify: clean apt cache

  - git: repo={{ ohmyzsh_repo }} version= {{ ohmyzsh_branch }} dest=/etc/skel/.oh-my-zsh accept_hostkey=true update=no

  - template: src=.zshrc.j2 dest=/etc/skel/.zshrc backup=yes

  - shell: |
      for a in $(ls {{ ohmyzsh_users_home_base_dir }}); do
        cp -r /etc/skel/.zshrc /etc/skel/.oh-my-zsh {{ ohmyzsh_users_home_base_dir }}/${a}/
        chown -R ${a}:${a} {{ ohmyzsh_users_home_base_dir }}/${a}/
        chsh -s /bin/zsh ${a}
      done
    when: ohmyzsh_users_home_base_dir is defined

  - shell: |
      cp -r /etc/skel/.zshrc /etc/skel/.oh-my-zsh {{ ohmyzsh_root_home }}
      chown -R root:root {{ ohmyzsh_root_home }}
      chsh -s /bin/zsh root
    when: ohmyzsh_root_home is defined
