---
# tasks file for oh-my-zsh

  - apt: name={{ item }} state=latest
    when: ansible_pkg_mgr == 'apt'
    sudo: true
    with_items:
      - zsh
      - git
    notify: clean apt cache

  - yum: name={{ item }} state=latest
    when: ansible_pkg_mgr == 'yum'
    sudo: true
    with_items:
      - zsh
      - git
    notify: clean yum cache

  - git: repo=git://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh accept_hostkey=true update=no

  - template: src=templates/.zshrc.j2 dest=~/.zshrc

  - user: name={{ ansible_env.USER }} shell=/bin/zsh
    sudo: true
    
