---
# handlers file for oh-my-zsh

  - name: clean apt cache
    shell: apt-get -y autoremove && apt-get -y autoclean
    sudo: true

  - name: clean yum cache
    shell: yum -y clean all
    sudo: true
